version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - newman/newman-run:
          collection: ./tests/TestingFlowSwaggerPetStore/tests/ 

workflows:
  example-workflow:
    jobs:
      - newman-job