version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./tests/TestingFlowSwaggerPetStore.postman_collection.json
          environment: ./env/SwaggerPetStore.postman_environment.json
workflows:
  postman-workflow:
    jobs:
      - newman-collection-run