version: 2.1
orbs:
  newman-orb: charge-tech/newman-orb@1.0.0
jobs:
  newman-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - newman-orb/newman-run:
          collection: ./tests/TestingFlowSwaggerPetStore.postman_collection.json 

workflows:
  postman-workflow:
    jobs:
      - newman-job